language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

#services: redis

before_script:
  - composer self-update
  - composer update
  - phpenv --version
  - phpenv versions

script:
  - php vendor/bin/atoum