#!/usr/bin/env php
<?php
// TestWebService.php

require __DIR__.'/vendor/autoload.php';

use Mactronique\TestWs\Command\TestUnitCommand;
use Symfony\Component\Console\Application;

$application = new Application('Test WebService', '1.2.0');
$application->add(new TestUnitCommand());
$application->run();
